version: '3.9'
services:
    db:
        image: mysql:8
        container_name: draw_my_today
        restart: always
        environment:
            MYSQL_DATABASE: draw_my_today_db
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Seoul
        volumes:
            - .dbdata:/var/lib/mysql
        ports:
            - '3306:3306'