spring:
    profiles:
        active: ${profile}
        include: oauth, aws, openai
encryptor:
    secret:
        key: ${ENCRYPTOR_SECRET_KEY}
presigned-image:
    expiration:
        admin-diaries: ${PRESIGNED_IMAGE_EXPIRATION_ADMIN_DIARIES}

