openai:
    api:
        key: ${OPENAI_API_KEY}
    dalle:
        url: ${DALLE_API_URL}
    gpt:
        chat_completions_prompt: ${GPT_CHAT_COMPLETIONS_PROMPT}
        chat_completions_regenerate_prompt: ${GPT_CHAT_COMPLETIONS_REGENERATE_PROMPT}